apiVersion: apps/v1
kind: Deployment
metadata:
  name: knodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knodeapp
  template:
    metadata:
      labels:
        app: knodeapp
    spec:
      containers:
        - name: knodeapp
          image: norman404/appnode:<IMAGE_TAG>
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: knodeapp-service
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: knodeapp
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: knodeapp-ingress
  annotations:
    cert-manager.io/issuer: letsencrypt-nginx
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - knodeapp.clase2023.molcajete.dev
    secretName: letsencrypt-nginx
  rules:
  - host: knodeapp.clase2023.molcajete.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: knodeapp-service
            port:
              number: 3000